site_name: MitoTNT
nav:
    - 'Home': 'index.md'
    - 'Installation': 'installation.md'
    - 'Data Preparation': 'data_preparation.md'
    - 'Tracking': 'tracking.md'
    - 'Visualization': 'visualization.md'
    - 'Detect Fusion/Fission': 'detect_remodeling.md'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
