site_name: MitoTNT
nav:
    - 'Home': 'index.md'
    - 'Installation': '1_installation.md'
    - 'Data preparation': '2_data_preparation.md'
    - 'Tracking': '3_tracking.md'
    - 'Visualization': '4_visualization.md'
    - 'Detect fusion/fission': '5_detect_remodeling.md'
    - 'Post-tracking analysis': '6_post_analysis.md'
theme:
    name: material
plugins:
    - mkdocs-video
